"""initial migration

Revision ID: b3da96c1f065
Revises: 
Create Date: 2016-12-24 01:25:48.688309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3da96c1f065'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('catname', sa.String(length=64), nullable=True))
    op.create_unique_constraint(None, 'roles', ['catname'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'catname')
    # ### end Alembic commands ###
